apiVersion: v1
kind: Service
metadata:
  name: shinobi
  namespace: shinobi
  annotations:
    metallb.universe.tf/address-pool: shinobi-pool
spec:
  selector:
    app: shinobi
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
